In [4]:
arr = np.ones((3,4,5),dtype=np.float64)

In [6]:
arr.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
arr.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
arr

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [10]:
arr = np.arange(3)

In [11]:
arr

array([0, 1, 2])

In [13]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [14]:
arr = np.random.randn(2,2)

In [15]:
arr

array([[ 0.27761542,  0.10983993],
       [-1.10238769, -0.95459671]])

In [20]:
np.tile(arr,(2,2))

array([[ 0.27761542,  0.10983993,  0.27761542,  0.10983993],
       [-1.10238769, -0.95459671, -1.10238769, -0.95459671],
       [ 0.27761542,  0.10983993,  0.27761542,  0.10983993],
       [-1.10238769, -0.95459671, -1.10238769, -0.95459671]])

In [22]:
arr = np.random.randn(4,3)

In [23]:
arr

array([[-0.63871146,  0.40110339, -0.49453588],
       [ 0.5471106 ,  0.15711232,  0.43443078],
       [-0.52099328, -0.72753641, -0.29563914],
       [-1.11356155, -0.20423809,  0.27867317]])

In [26]:
arr.mean(0)

array([-0.43153892, -0.0933897 , -0.01926777])

In [29]:
arr - arr.mean(0)

array([[-0.20717254,  0.49449309, -0.47526811],
       [ 0.97864952,  0.25050202,  0.45369854],
       [-0.08945436, -0.63414671, -0.27637137],
       [-0.68202262, -0.11084839,  0.29794094]])

In [31]:
arr.mean(1)

array([-0.24404798,  0.37955123, -0.51472294, -0.34637549])

In [32]:
arr

array([[-0.63871146,  0.40110339, -0.49453588],
       [ 0.5471106 ,  0.15711232,  0.43443078],
       [-0.52099328, -0.72753641, -0.29563914],
       [-1.11356155, -0.20423809,  0.27867317]])

In [35]:
arr[:,arr[0].argsort()]

array([[-0.63871146, -0.49453588,  0.40110339],
       [ 0.5471106 ,  0.43443078,  0.15711232],
       [-0.52099328, -0.29563914, -0.72753641],
       [-1.11356155,  0.27867317, -0.20423809]])