In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
%matplotlib inline

In [3]:
df1 = DataFrame({'key':['a','b','a','c','a','a','b'],'data1':range(7)})

In [4]:
df2 = DataFrame({'key':['a','b','d'],'data2':range(3)})

In [8]:
df1

data1 key
0      0   a
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [9]:
df2

data2 key
0      0   a
1      1   b
2      2   d

#### pd.merge相当于sql内连接

In [12]:
pd.merge(df2,df1,on='key')

data2 key  data1
0      0   a      0
1      0   a      2
2      0   a      4
3      0   a      5
4      1   b      1
5      1   b      6

In [13]:
df1 = DataFrame({'lkey':['a','b','a','c','a','a','b'],'data1':range(7)})
df2 = DataFrame({'rkey':['a','b','d'],'data2':range(3)})

In [17]:
pd.merge(df1,df2,left_on='lkey',right_on='rkey')

data1 lkey  data2 rkey
0      0    a      0    a
1      2    a      0    a
2      4    a      0    a
3      5    a      0    a
4      1    b      1    b
5      6    b      1    b

In [21]:
pd.merge(df1,df2,left_on='lkey',right_on='rkey',how='left')

data1 lkey  data2 rkey
0      0    a    0.0    a
1      1    b    1.0    b
2      2    a    0.0    a
3      3    c    NaN  NaN
4      4    a    0.0    a
5      5    a    0.0    a
6      6    b    1.0    b

In [22]:
left = DataFrame({'key1':['foo','foo','bar'],'key2':['one','two','one'],'lval':[1,2,3]})
right = DataFrame({'key1':['foo','foo','bar','bar'],'key2':['one','one','one','two'],'lval':[4,5,6,7]})

In [23]:
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [24]:
right

key1 key2  lval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [33]:
pd.merge(left,right,on=['key1','key2'],how='left',suffixes=('_left','_right'),sort='key1')

key1 key2  lval_left  lval_right
0  bar  one          3         6.0
1  foo  one          1         4.0
2  foo  one          1         5.0
3  foo  two          2         NaN

In [34]:
left2 = DataFrame([[1,2],[3,4],[5,6]],index=['a','c','e'],columns=['ohio','nevada'])

In [35]:
left2

ohio  nevada
a     1       2
c     3       4
e     5       6

In [36]:
right2 = DataFrame([[7,8],[9,10],[11,12],[13,14]],index=['b','c','d','e'],columns=['missouri','alabama'])

In [37]:
right2

missouri  alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [40]:
left2.join(right2,how='outer')

ohio  nevada  missouri  alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [41]:
arr = np.arange(12).reshape(3,4)

In [42]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [44]:
np.concatenate([arr,arr],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
np.concatenate([arr,arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11]])

In [47]:
s1 = Series([0,1],index=['a','b'])
s2 = Series([2,3,4],index=['c','d','e'])
s3 = Series([5,6],index=['f','g'])

In [48]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [49]:
pd.concat([s1,s2,s3],axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [50]:
s4 = pd.concat([s1*5,s3])

In [51]:
s4

a    0
b    5
f    5
g    6
dtype: int64

In [52]:
pd.concat([s1,s4])

a    0
b    1
a    0
b    5
f    5
g    6
dtype: int64

In [53]:
pd.concat([s1,s4],axis=1)

0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [54]:
pd.concat([s1,s4],axis=1,join='inner')

0  1
a  0  0
b  1  5

In [59]:
pd.concat([s1,s4],axis=1,join_axes=[['a','b','c','f']])

0    1
a  0.0  0.0
b  1.0  5.0
c  NaN  NaN
f  NaN  5.0

In [61]:
pd.concat([s1,s4],axis=0,keys=['s1','s4'])

s1  a    0
    b    1
s4  a    0
    b    5
    f    5
    g    6
dtype: int64

In [62]:
result = pd.concat([s1,s1,s3],keys=['one','two','three'])

In [63]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [69]:
result.unstack().unstack().unstack()

one  two  three
a  0.0  0.0    NaN
b  1.0  1.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [67]:
result.unique()

array([0, 1, 5, 6], dtype=int64)

In [70]:
result = pd.concat([s1,s1,s3],axis=1,keys=['one','two','three'])

In [72]:
result.unstack()

one    a    0.0
       b    1.0
       f    NaN
       g    NaN
two    a    0.0
       b    1.0
       f    NaN
       g    NaN
three  a    NaN
       b    NaN
       f    5.0
       g    6.0
dtype: float64

In [73]:
result

one  two  three
a  0.0  0.0    NaN
b  1.0  1.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [74]:
df1 = DataFrame(np.random.randn(3,4),columns=['a','b','c','d'])
df2 = DataFrame(np.random.randn(2,3),columns=['b','d','a'])

In [77]:
pd.concat([df1,df2],ignore_index=True)

a         b         c         d
0  1.316933  0.333763  0.553400  1.097166
1 -1.650044 -1.638107 -0.652438 -0.064264
2  0.484781 -0.127937 -0.135833  0.052357
3 -0.932894  0.484154       NaN  1.052963
4 -0.277699  0.553604       NaN  1.011768

In [80]:
pd.concat([s1,s1],verify_integrity=True)

ValueError: Indexes have overlapping values: ['a', 'b']